#!/bin/bash
while getopts ":f:d:a" opt; do
    case $opt in
        f) filename="$OPTARG"
        ;;
        d) foldername="$OPTARG"
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        ;;
    esac
done

if [ ! -z "$filename" ]; then
    ./bin/main "$filename"
elif [ ! -z "$foldername" ] && [ -z "$execute_all" ]; then
    for file in "$foldername"/*; do
        ./bin/main "$file"
        sleep 1
    done
else
    echo "Please specify either a filename or a foldername."
fi
