#!/bin/bash

while getopts "f:d:" opt; do
    case $opt in
        f) filename="$OPTARG"
        ;;
        d) foldername="$OPTARG"
        ;;
        \?) echo "Invalid option -$OPTARG" >&2
        ;;
    esac
done

if [ ! -z "$filename" ]; then
    ./bin/txt2bin "$filename" 
elif [ ! -z "$foldername" ]; then
    for file in "$foldername"/*; do
       ./bin/txt2bin "$file" 
    done
else
    echo "Please specify either a filename or a foldername."
fi
